version: '3'
services:
  mydocker1:
    image: ubuntu:18.04
    tty: true
    networks: 
      - my-shared-network
  mydocker2:
    image: ubuntu:18.04
    tty: true
    networks: 
      - my-shared-network
  mydocker3:
    image: ubuntu:18.04
    tty: true
    networks: 
      - my-private-network
  mydocker4:
    image: ubuntu:18.04
    tty: true
    networks: 
      - my-private-network
  mydocker5:
    image: ubuntu:18.04
    tty: true
    networks: 
      - my-private-network
      - my-shared-network
networks:
  my-shared-network: {}
  my-private-network: {}
